name: build_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-with-cmake:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j
