name: build_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-with-cmake:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson libglew-dev

      - run: mkdir -p grpc-dev

      - name: Download grpc-dev
        run: |
          curl -L https://github.com/zigen-project/grpc-dev/releases/download/0.0.1/grpc-dev-refs.heads.main-github-host.zip -o grpc-dev.zip
          unzip grpc-dev.zip
        working-directory: ./grpc-dev

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: zen-remote
          submodules: true
      
      - name: Build
        working-directory: ./zen-remote
        env:
          CXX: clang++
          CC: clang
        run: |
          cmake -B build -DZEN_REMOTE_GRPC_SYSROOT=$GITHUB_WORKSPACE/grpc-dev/native/Debug
          cmake --build build -j
